version: '3.7'
services:
  database:
    image: "postgres:13"
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=weatherdb
    volumes:
    - /var/lib/postgresql/data/
    networks:
      assignment-net:

  weather-collector-service:
    image: "weather-collector-service:0.1.0-SNAPSHOT"
    ports:
    - 8080:8080
    environment:
    - OPENWEATHER_SERVICE_ID=YOUR_API_KEY
    - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/weatherdb
    - SPRING_DATASOURCE_USERNAME=admin
    - SPRING_DATASOURCE_PASSWORD=admin
    links:
    - database
    networks:
      assignment-net:

networks:
  assignment-net: